blank_issues_enabled: false
contact_links:
  - name: Questions & general discussion
    url: https://github.com/thereisnotime/tint-cheats/discussions
    about: Ask questions or chat with the community over in Discussions.
